### ISSUE TITLE
Get intermediary lane mask

### ISSUE THREAD

**Issue by emeryanalytics** [Turoad/lanedet#10]
Hi,

Thanks for the awesome work.
In 'tools\detect.py', I wonder if there is a way for me to get the intermediary lane segmentation mask from the models (i.e. as opposed to lane point coordinates)?

Thanks

**Comment by Turoad** [comment]
What's the  intermediary lane segmentation mask?

**Comment by emeryanalytics** [comment]
Sorry, I meant the probability map that represent which areas are likely lanes.
I think I figure it out: For `lane_seg` heads, I can get it from `output['seg']`.

Thanks. I will chose this item.

**Comment by Turoad** [comment]
Yes, you are right. You can get segmentation result from `output['seg']` in RESA. But if you train other methods like LaneATT, you cannot get it.

**Comment by emeryanalytics** [comment]
Got it. Thanks for the clarification.
