### ISSUE TITLE
关于一个奇怪的 UserWarning

### ISSUE THREAD

**Issue by qklee-lz** [Turoad/lanedet#11]
您好！
无论是我运行train/val/detect, 都会报这样一个错：UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
 
顺便问一下，用你另一个代码仓（resa）训练出来的pth文件，配合这个lanedet是不是无法使用，好像lanedet的resa结构把exist删掉了。

**Comment by Turoad** [comment]
It's just a warning. Take it easy.
The model in repo [resa](https://github.com/ZJULearning/resa) is slightly different with this repo. I think you can refer to this: https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686 to make the model fit for this repo.
