### ISSUE TITLE
Output Format

### ISSUE THREAD

**Issue by BehiceB** [Turoad/lanedet#12]
Hello,
i want to extract the model and i want to get the output tensor format because of tracer can not infer dict type. How can i get the output this format? Thank you in advance for your reply

**Comment by Turoad** [comment]
Sorry, I don't know what's the tracer.  Most dict outputs are in the lanedet/models/heads, like this: https://github.com/Turoad/lanedet/blob/main/lanedet/models/heads/exist_head.py#L34.  You can try remove it.

**Comment by AbdulFMS** [comment]
> he lanedet/models/heads, like

did it work to change the format of the output!?

**Comment by AbdulFMS** [comment]
@BehiceB can you share here the result please!
