### ISSUE TITLE
how to support distributed training ？

### ISSUE THREAD

**Issue by Wolfwjs** [Turoad/lanedet#13]
Do you support slurm's single-machine multi-card training on the cluster?
FileExistsError: [Errno 17] File exists: 'work_dirs/TuSimple/20210802_193905_lr_3e-02_b_8'

**Comment by Turoad** [comment]
Sorry, I have no cluster to test it.
However, in my machine, it works well with single-machine multi-card.

**Comment by Wolfwjs** [comment]
> Sorry, I have no cluster to test i

**Comment by Wolfwjs** [comment]
> Sorry, I have no cluster to test it.
> However, in my machine, it works well with single-machine multi-card.

Thanks for your reply!
