### ISSUE TITLE
A consultation on the results

### ISSUE THREAD

**Issue by Starboy-at-earth** [Turoad/lanedet#19]
Dear Author:
        Could you please tell me whether the results reported in the paper can be reproduced by your kind re-implementation? How much score do you get on CULane and Tusimple, respectively ? By the way, could you please tell me how many GPUs do you use to generate the results? And can I have you in my contact list? My qq account is 2667004002. Look forward to your reply...

**Comment by Turoad** [comment]
You can see the README.md in corresponding folder, for example in [configs/resa](https://github.com/Turoad/lanedet/tree/main/configs/resa), it has the score on CULane and Tusimple. The results are consitent with the paper's results.  Most results are based on one GPU.

**Comment by Starboy-at-earth** [comment]
@Turoad Dear author:
Do you have any guess on why other methods are inferior to CondLaneNet in terms of accuracy? Positive and negative samples are not balanced?

**Comment by Turoad** [comment]
I think the network design or lane format (segmentation, row cls, or anchors) may play a important role in final accuracy. Currently, I'm  researching about these methods. I may update the details about this question later.
