### ISSUE TITLE
Inference code

### ISSUE THREAD

**Issue by cf206cd** [Turoad/lanedet#2]
It would be nicer if you can add inference code! And why there is no MobileNet in backbone? Does it not work well for this task?

**Comment by Turoad** [comment]
Thank for your interest.

What you needs in inference code, e.g., do visualization?
Currently, we support visualization in validate phase by adding `--view`.

As for MoblieNet, We haven't tested it. We will consider testing it and updating the configs. It may have faster inference speed but relatively low accuracy.

**Comment by cf206cd** [comment]
Well, not only visualization, some (including me) may need to deploy it on some embedding devices, so maybe we can implement a class to do inference without complicated config and data loader?

**Comment by Turoad** [comment]
OK, I will consider add the inference code. The config cannot be removed. We need the config to define network, preprocess or others.

**Comment by cf206cd** [comment]
And maybe another advice... It would be better if you can change the input of the model to be only images just like mmdetection. It seems to be a batch with both images and labels now and it`s not convenient for inference. Thank you for your good job!

**Comment by Turoad** [comment]
The input is a `dict`. If you don't have labels, just get the `img`, like this: https://github.com/Turoad/lanedet/blob/main/lanedet/models/net/detector.py#L19.
If the dataset don't have any label, we can handle this case. I don't think it's inconvenient.

**Comment by Turoad** [comment]
By the way, we don't have labels during validate in a batch. Do you run the code and get labels?

**Comment by Turoad** [comment]
@cf206cd I have added the MobileNetV2(https://github.com/Turoad/lanedet/blob/main/configs/laneatt/resnet18_culane.py) and the `tools/detect.py`.

**Comment by cf206cd** [comment]
Wow! Amazing! Thank you so much!
