### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for DataParallel

### ISSUE THREAD

**Issue by wuyunnben** [Turoad/lanedet#23]
Hi, I run RESA model inference  with
`python tools/detect.py configs/resa/resa34_tusimple.py --img 1.png --load_from weight/tusimple_resa34.pth --savedir ./vis`
tusimple_resa34.pth download from the 'https://github.com/ZJULearning/resa'
but got 
net.load_state_dict(pretrained_model['net'], strict=True)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	Missing key(s) in state_dict: "module.aggregator.conv_d0.weight", ..........
Any advise, very thanks

**Comment by Turoad** [comment]
Please use this repo's pretrained model. This repo has a little difference with https://github.com/ZJULearning/resa.
