### ISSUE TITLE
ValueError: bbox_params must be specified for bbox transformations

### ISSUE THREAD

**Issue by jiaobingle** [Turoad/lanedet#25]
when run 'python train.py configs/condlane/resnet101_culane.py --gpus0' ,it shows the error,and info shows location as follows:
lanedet-condlane/lanedet/datasets/process/alaug.py", line 160, in __call__
    bbox_labels=bbox_labels)

i check this function, and bboxes=None,bbox_labels=None
![image](https://user-images.githubusercontent.com/15828267/136876155-fea49235-a158-4d04-bb93-15b13be7ee2c.png)

How can i solve this issue,thx!

**Comment by chenyonx** [comment]
modify version of albumentation can run well?
