### ISSUE TITLE
KeyError: 'meta'

### ISSUE THREAD

**Issue by daigang896** [Turoad/lanedet#27]
Hello, 

when run: 
python main.py configs/scnn/resnet18_tusimple.py --validate --load_from scnn_r18_tusimple.pth --gpus 0 --view,  the following error error occurred.

lanedet/engine/runner.py", line 116, in validate
    self.val_loader.dataset.view(output, data['meta'])
KeyError: 'meta'

when not add --view，it's normal.

What is the problem and how to solve it?

**Comment by gautamjain1009** [comment]
I have the same issue I have tried with different models, datasets. The issue prevails. I even checked your data-loader. Kindly resolve this issue. Thanks

**Comment by Turoad** [comment]
Sorry for late. @gautamjain1009 @daigang896 
This commit https://github.com/Turoad/lanedet/commit/d36ba736d0b30574563e4e7b39e86516cb75b1c5 can fix this issue.
Have a try!
