### ISSUE TITLE
KeyError: 'img_metas'

### ISSUE THREAD

**Issue by AndreHoffmannWIMI** [Turoad/lanedet#28]
Dear author,

I'm quiet new to the framework and tried to adapt some of the code for my own dataset. 
After writing the dataset.py and the config based on the resnet50_culane.py i get this error when i start the training:

 File "/projekte/lanedet/lanedet/lanedet/models/heads/condlane.py", line 867, in forward_train
    print(batch['img_metas'])
KeyError: 'img_metas'

I understood that the  data['img_metas'] is created in the preprocessing while executing collect_lane. 
Isn't this information just overwritten in  the ToTensorprocess:

 def __call__(self, sample):
        data = {}
        if len(sample['img'].shape) < 3:
            sample['img'] = np.expand_dims(sample['img'], -1)
        for key in self.keys:
            data[key] = to_tensor(sample[key])
        data['img'] = data['img'].permute(2, 0, 1)
        return data

How does the data['img_metas']-information preserve in the execution of the normal resnet50_culane.py?

@edit i tried the esnet50_culane.py with normal culane_dataset. Doesnt work for it either.

**Comment by AndreHoffmannWIMI** [comment]
I looked a bit in the version history and found the change where you delete the "img_metas", reverted it, still errors. Is there a version in the repository where training the condlane/resnet50_culane.py actually works?

**Comment by zqh0253** [comment]
Hi, I meet the same problem. Have you solved it?

**Comment by AndreHoffmannWIMI** [comment]
No, i just switched to the resa detector, which worked at the end.

**Comment by Turoad** [comment]
This commit https://github.com/Turoad/lanedet/commit/d36ba736d0b30574563e4e7b39e86516cb75b1c5 can fix this issue.
Have a try!
