### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by hzzzzjzyq** [Turoad/lanedet#30]
python setup.py build develop

File "/home/zzj/anaconda3/envs/Lanedet/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 275, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

ubuntu20.04 what can i do？

**Comment by qslia** [comment]
hello, can you tell how to fix this bug, i have met this bug too

**Comment by Aliweka2020** [comment]
same error here

**Comment by gautamjain1009** [comment]
same error has anyone solved it?

**Comment by GeneralJing** [comment]
same error here.

**Comment by Turoad** [comment]
I have no idea, since i don't  have this issue.
Any more information about your setting?

**Comment by Turoad** [comment]
I will close this issue first. Feel free to reopen it if you have any questions.
