### ISSUE TITLE
it seems that the sigmoid function used twice

### ISSUE THREAD

**Issue by hfz223322** [Turoad/lanedet#32]
https://github.com/Turoad/lanedet/blob/210709066886e4906c8d3ab4d9173785ef07c65d/lanedet/models/heads/exist_head.py#L32
Dear author, thanks for your code. I find in exist_head.py, the output of fc10 was then put into an sigmoid function, but in lane_seg.py, you used BCEWithLogitsLoss() to calculate BCE loss, it seems that the sigmoid function was used twice.

**Comment by Turoad** [comment]
You can refer this issue: https://github.com/ZJULearning/resa/issues/29
