### ISSUE TITLE
运行setup.py 报错

### ISSUE THREAD

**Issue by cedar33** [Turoad/lanedet#33]
/home/ma-user/anaconda3/envs/lanedet/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:66:23: error: could not convert ‘torch::kLeakyReLU’ from ‘const torch::enumtype::kLeakyReLU’ to ‘torch::nn::init::NonlinearityType {aka c10::variant<torch::enumtype::kLinear, torch::enumtype::kConv1D, torch::enumtype::kConv2D, torch::enumtype::kConv3D, torch::enumtype::kConvTranspose1D, torch::enumtype::kConvTranspose2D, torch::enumtype::kConvTranspose3D, torch::enumtype::kSigmoid, torch::enumtype::kTanh, torch::enumtype::kReLU, torch::enumtype::kLeakyReLU>}’
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
---
报错很长，截取了最后一点，看了看好像就我一个人遇到这个问题
```
python 3.6
cuda Version: 10.2
torch==1.6.0
torchvision==0.7.0

**Comment by shuizaola** [comment]
我也报这个错误

**Comment by Turoad** [comment]
有可能是nvcc的版本问题，用的哪个版本。
`nvcc --version`

**Comment by Turoad** [comment]
I will close this issue first. Feel free to reopen it if you have any questions.
