### ISSUE TITLE
--view for culane dataset doesnt work

### ISSUE THREAD

**Issue by AirSmoke031** [Turoad/lanedet#34]
Hi, when i add --view for culane dataset it doesnt work with the error
 Traceback (most recent call last):
  File "main.py", line 65, in <module>
    main()
  File "main.py", line 33, in main
    runner.validate()
  File "/home/grgur/lanedet/lanedet/engine/runner.py", line 116, in validate
    self.val_loader.dataset.view(output, data['meta'])
KeyError: 'meta'

For the TuSimple dataset it added to the vizualization file with no problem, but for culane somehow it doesnt work.
Please help.

**Comment by Turoad** [comment]
Fixed. Refer these issues: https://github.com/Turoad/lanedet/issues/28, https://github.com/Turoad/lanedet/issues/27
