### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by shuizaola** [Turoad/lanedet#35]
为什么运行python main.py configs/condlane/resnet101_culane.py --gpus 0 1后输出configs里的内容就卡住不动了 ？有谁知道吗

**Comment by Turoad** [comment]
需要多等一会吧。在做一些work_dirs里面的日志的初始工作。比如https://github.com/Turoad/lanedet/blob/main/lanedet/utils/recorder.py#L52

**Comment by shuizaola** [comment]
> 需要多等一会吧。在做一些work_dirs里面的日志的初始工作。比如https://github.com/Turoad/lanedet/blob/main/lanedet/utils/recorder.py#L52

是在做work_dirs的日志，但是work_dirs里面是把数据集和程序都copy过来了，而且等了几个小时都没复制完，很慢

**Comment by Turoad** [comment]
确认你是不是放了大文件在lanedet目录下。正常不会等太久。

另外，你可以考虑注释掉这行代码：https://github.com/Turoad/lanedet/blob/main/lanedet/utils/recorder.py#L52

**Comment by shuizaola** [comment]
> 确认你是不是放了大文件在lanedet目录下。正常不会等太久。
> 
> 另外，你可以考虑注释掉这行代码：https://github.com/Turoad/lanedet/blob/main/lanedet/utils/recorder.py#L52

谢谢，我试试，放了数据集在目录里

**Comment by Turoad** [comment]
嗯，如果在拷贝数据集的话。
建议软连接即可，比如`ln -s $CULANEROOT data/CULane`。
另外，如果不需要拷贝代码到work_dirs的话，还是可以考虑注释。
