### ISSUE TITLE
Can't convert the model to onnx

### ISSUE THREAD

**Issue by AbdulFMS** [Turoad/lanedet#36]
`sample_input = torch.rand((32, 3, 3, 3))

torch.onnx.export(
    net1.module,                  # PyTorch Model
    sample_input,                    # Input tensor
    '/content/drive/MyDrive/MobileNetV2-model-onnx.onnx',        # Output file (eg. 'output_model.onnx')
    opset_version = 12,       # Operator support version
    input_names = ['input'],   # Input tensor name (arbitary)
    output_names = ['output'] # Output tensor name (arbitary)
)`

Got this Error:

> TypeError                                 Traceback (most recent call last)
> [<ipython-input-47-7b71912330d3>](https://localhost:8080/#) in <module>()
>       5     opset_version=12,       # Operator support version
>       6     input_names=['input'],   # Input tensor name (arbitary)
> ----> 7     output_names=['output'] # Output tensor name (arbitary)
>       8 )
> 
>      21     def forward(self, batch):
>      22         output = {}
> ---> 23         fea = self.backbone(batch['img'])
>      24 
>      25         if self.aggregator:
> 
> TypeError: new(): invalid data type 'str'

**Comment by AbdulFMS** [comment]
@Turoad Can you help Please!

**Comment by Turoad** [comment]
@AbdulFMS I haven't tried onnx. I may add onnx support later, but it may take some time.

**Comment by AbdulFMS** [comment]
> @AbdulFMS I haven't tried onnx. I may add onnx support later, but it may take some time.

Thank You! it will be great if you could provide that, because I have tried and spend alot of time on it but I got a RuntimeError:

Exporting the operator eye to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.

**Comment by AbdulFMS** [comment]
it was the problem in the torch version 1.6, after I used the latest version of torch on Colab, I managed to fix this, but I got a CUDA runtime error:
> RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

this is my colab notebook:

https://colab.research.google.com/drive/18udIh8tNJvti7jKmR4jRaRO-oYDgRmvA?usp=sharing

do you have any idea about how to solve that, and is it possible to use this model without CUDA!? @Turoad

**Comment by Turoad** [comment]
You might upgrade your nvidia driver to use higher version pytorch.

**Comment by luan1412167** [comment]
> it was the problem in the torch version 1.6, after I used the latest version of torch on Colab, I managed to fix this, but I got a CUDA runtime error:
> 
> > RuntimeError: CUDA error: device-side assert triggered
> > CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
> > For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> 
> this is my colab notebook:
> 
> https://colab.research.google.com/drive/18udIh8tNJvti7jKmR4jRaRO-oYDgRmvA?usp=sharing
> 
> do you have any idea about how to solve that, and is it possible to use this model without CUDA!? @Turoad

Can you share me how you deal with this issue?
Thanks
