### ISSUE TITLE
ImportError: cannot import name 'nms_impl' from partially initialized module 'lanedet.ops' (most likely due to a circular import) (/home/projects/lanedet/lanedet/ops/__init__.py)

### ISSUE THREAD

**Issue by GeneralJing** [Turoad/lanedet#37]
when i execute the commond:
python main.py configs/resa/resa50_culane.py --validate --load_from culane_resnet50.pth --gpus 0 --view
i met the errors.

**Comment by GeneralJing** [comment]
solved.

**Comment by CompliceU** [comment]
@GeneralJing Hello, I also had the same problem and don't know how you solved it， Thx

**Comment by Turoad** [comment]
@CompliceU you should follow README.md and compile this repo.

**Comment by sjtuljw520** [comment]
I have follow README and install the lanedet pakage successfully, but still encounter the same problem, anyone can help me?

**Comment by gm24med** [comment]
> solved.

hey, can i know how did you solve the problem because i'm still facing it .

**Comment by Salary-only-17k** [comment]
the same problem
