### ISSUE TITLE
inference does not seem to work correctly (input image not scaled correctly?)

### ISSUE THREAD

**Issue by jack-zhang-123** [Turoad/lanedet#4]
Hi there, thank you for this very helpful resource. However I was wondering if there is something wrong with some of the inference code, in particular the given code in the README for RESA resnet34 trained on CUlanes. I fed the following image in: 
![image](https://user-images.githubusercontent.com/77084483/120126103-063b9c80-c170-11eb-8f22-62ec60e7ccad.png)

And received the following output:

![image](https://user-images.githubusercontent.com/77084483/120126132-194e6c80-c170-11eb-8a28-4ae008f45743.png)

I was wondering why this is and if there is anything I am doing wrong or if this is a problem with the uploaded models themselves. If it is helpful please find attached the colab notebook I was using: https://colab.research.google.com/drive/1WI0T-s0dRvewnkm_qrwvM3NOjNiMEXXv?usp=sharing

Thank you in advance.

**Comment by Turoad** [comment]
I have tested it on CULane dataset, it works well.
It seems you are not using the CULane dataset, maybe the input scale is not same with CULane dataset,  you may change the size in config file: https://github.com/Turoad/lanedet/blob/a451684bbda295c50a58a6f00dba59172489d2c7/configs/resa/resa34_culane.py#L71-L72
