### ISSUE TITLE
Your Resnet wrapper feature size vs OG pytorch resnet feature size (Last layer) 

### ISSUE THREAD

**Issue by gautamjain1009** [Turoad/lanedet#41]
Hey, I was looking into your implementation of the Resnet wrapper. Everything seems identical apart from the feature map sizes. I see that you have tried to upsample the feature maps size somehow by increasing the padding and dilation parameters, does that affect your training accuracy? It will save me a lot of training time as I have really limited resources. 

Thanks in advance!

**Comment by Turoad** [comment]
Which configs do you use?

**Comment by gautamjain1009** [comment]
For example, if I use scnn with resnet18. (configs/scnn/resnet18_tusimple.py). I see that in all the configs, basically different variants of resnet  via your resnet wrapper, last layer feature maps size is a little but upsampled than the OG pytorch's resnet.

**Comment by Turoad** [comment]
This config  is only used in RESA or SCNN. These methods are segmentation-based, they need larger size of feature map to keep high accuracy.
