### ISSUE TITLE
LaneATT for six lanes

### ISSUE THREAD

**Issue by balajiiitg** [Turoad/lanedet#42]
HI I need to train on six lanes. Can you help me out. 
Thanks in Advance

**Comment by Turoad** [comment]
Firstly, I think you need a dataset with six lanes annotations. For dataset preparation, you can  try follow methods:
1.  Transform your annotations to a format that is already used in the project, like CULane.
2. Create a class to load your images and labels in a custom format like [CULane](https://github.com/Turoad/lanedet/blob/main/lanedet/datasets/culane.py).

For training, you may change the `max_lanes`  like [this file](https://github.com/Turoad/lanedet/blob/main/configs/laneatt/resnet18_culane.py#L16) to 6.

I'm not sure whether there are other situations or not. Have a try, good luck.
