### ISSUE TITLE
curvature estimation 

### ISSUE THREAD

**Issue by k-nayak** [Turoad/lanedet#43]
Hello, I would like to know if there is any way to get real-time lane detection and curvature detection using deep learning. I have seen traditional computer vision algorithms but I am looking for a Deep Learning model that could help me out with this. Any suggestions will be very helpful. Thanks in advance.

**Comment by Turoad** [comment]
Currently, this repo supports lane detection by deep learning, including both straight or curve lanes. 

What's the curvature detection?

**Comment by k-nayak** [comment]
I wanted to know about the computation of curvature of the lane in real-time.

**Comment by Turoad** [comment]
curvature? Is this https://en.wikipedia.org/wiki/Curvature?

**Comment by k-nayak** [comment]
Yes. The plane curve. Kappa = 1/R

Kappa is curvature and R is the radius

I want to know if we can do curve fitting and get the curvature in using the robust lane detection of the model.

**Comment by Turoad** [comment]
Maybe you can try the curve-based method, like PolyLaneNet or LSTR. These methods predict the curve of lanes as a polynomial regression task.

**Comment by k-nayak** [comment]
I am trying to implement ultra fast lane detection model. And use curve base method to detect curvature. I will try lstr ans poly lanenet, if it doesn't work. Thanks for the suggestion.

**Comment by Turoad** [comment]
If you are using UFLD, the curvature of lanes is calculated from post-processing?

**Comment by k-nayak** [comment]
Not really, I plan on using the traditional method of the perspective transform to BEV and calculating curvature using the detected lanes from the network.

**Comment by Turoad** [comment]
If so, I think you can also try other models like LaneATT (anchor-based method), RESA (segmentation-based method).
