### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'astype'.

### ISSUE THREAD

**Issue by Lufei-github** [Turoad/lanedet#5]
![图片](https://user-images.githubusercontent.com/47933628/122233818-f2719380-ceee-11eb-8b9d-cd15474b5c7c.png)

**Comment by Lufei-github** [comment]
作者你好，我遇到一些问题！如上，它显示NoneType has no attribute astype,对应代码中
img = cv2.imread(data_info['img_path']).astype(np.float32)
但是我数据集明明已经放进去了，所以很困惑
您能给我些帮助吗？万分感激

**Comment by Turoad** [comment]
Maybe you don't put the imageset into the right place. I have updated the code, pull it and run again.
