### ISSUE TITLE
在windows下面运行setup.py报错

### ISSUE THREAD

**Issue by minhoooo1** [Turoad/lanedet#51]
PS C:\Users\MINHOO\Desktop\lanedet-main> python setup.py build develop
C:\Users\MINHOO\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should 
be satisfied by a PEP 517 installer.
  warnings.warn(
running build
running build_py
creating build
creating build\lib.win-amd64-3.8
creating build\lib.win-amd64-3.8\lanedet
copying lanedet\__init__.py -> build\lib.win-amd64-3.8\lanedet
creating build\lib.win-amd64-3.8\lanedet\datasets
copying lanedet\datasets\base_dataset.py -> build\lib.win-amd64-3.8\lanedet\datasets
copying lanedet\datasets\culane.py -> build\lib.win-amd64-3.8\lanedet\datasets
copying lanedet\datasets\registry.py -> build\lib.win-amd64-3.8\lanedet\datasets
copying lanedet\datasets\tusimple.py -> build\lib.win-amd64-3.8\lanedet\datasets
copying lanedet\datasets\__init__.py -> build\lib.win-amd64-3.8\lanedet\datasets
creating build\lib.win-amd64-3.8\lanedet\engine
copying lanedet\engine\optimizer.py -> build\lib.win-amd64-3.8\lanedet\engine
copying lanedet\engine\registry.py -> build\lib.win-amd64-3.8\lanedet\engine
copying lanedet\engine\runner.py -> build\lib.win-amd64-3.8\lanedet\engine
copying lanedet\engine\scheduler.py -> build\lib.win-amd64-3.8\lanedet\engine
copying lanedet\engine\__init__.py -> build\lib.win-amd64-3.8\lanedet\engine
creating build\lib.win-amd64-3.8\lanedet\models
copying lanedet\models\registry.py -> build\lib.win-amd64-3.8\lanedet\models
copying lanedet\models\__init__.py -> build\lib.win-amd64-3.8\lanedet\models
creating build\lib.win-amd64-3.8\lanedet\ops
copying lanedet\ops\nms.py -> build\lib.win-amd64-3.8\lanedet\ops
copying lanedet\ops\__init__.py -> build\lib.win-amd64-3.8\lanedet\ops
creating build\lib.win-amd64-3.8\lanedet\utils
copying lanedet\utils\config.py -> build\lib.win-amd64-3.8\lanedet\utils
copying lanedet\utils\culane_metric.py -> build\lib.win-amd64-3.8\lanedet\utils
copying lanedet\utils\logger.py -> build\lib.win-amd64-3.8\lanedet\utils
copying lanedet\utils\net_utils.py -> build\lib.win-amd64-3.8\lanedet\utils
copying lanedet\utils\recorder.py -> build\lib.win-amd64-3.8\lanedet\utils
copying lanedet\utils\registry.py -> build\lib.win-amd64-3.8\lanedet\utils
copying lanedet\utils\tusimple_metric.py -> build\lib.win-amd64-3.8\lanedet\utils
copying lanedet\utils\visualization.py -> build\lib.win-amd64-3.8\lanedet\utils
copying lanedet\utils\__init__.py -> build\lib.win-amd64-3.8\lanedet\utils
creating build\lib.win-amd64-3.8\lanedet\datasets\process
copying lanedet\datasets\process\alaug.py -> build\lib.win-amd64-3.8\lanedet\datasets\process
copying lanedet\datasets\process\collect_lane.py -> build\lib.win-amd64-3.8\lanedet\datasets\process
copying lanedet\datasets\process\generate_lane_cls.py -> build\lib.win-amd64-3.8\lanedet\datasets\process
copying lanedet\datasets\process\generate_lane_line.py -> build\lib.win-amd64-3.8\lanedet\datasets\process
copying lanedet\datasets\process\process.py -> build\lib.win-amd64-3.8\lanedet\datasets\process
copying lanedet\datasets\process\transforms.py -> build\lib.win-amd64-3.8\lanedet\datasets\process
copying lanedet\datasets\process\__init__.py -> build\lib.win-amd64-3.8\lanedet\datasets\process
creating build\lib.win-amd64-3.8\lanedet\models\aggregators
copying lanedet\models\aggregators\aspp.py -> build\lib.win-amd64-3.8\lanedet\models\aggregators
copying lanedet\models\aggregators\resa.py -> build\lib.win-amd64-3.8\lanedet\models\aggregators
copying lanedet\models\aggregators\scnn.py -> build\lib.win-amd64-3.8\lanedet\models\aggregators
copying lanedet\models\aggregators\transformer.py -> build\lib.win-amd64-3.8\lanedet\models\aggregators
copying lanedet\models\aggregators\__init__.py -> build\lib.win-amd64-3.8\lanedet\models\aggregators
creating build\lib.win-amd64-3.8\lanedet\models\backbones
copying lanedet\models\backbones\erfnet.py -> build\lib.win-amd64-3.8\lanedet\models\backbones
copying lanedet\models\backbones\mobilenet.py -> build\lib.win-amd64-3.8\lanedet\models\backbones
copying lanedet\models\backbones\resnet.py -> build\lib.win-amd64-3.8\lanedet\models\backbones
copying lanedet\models\backbones\vgg.py -> build\lib.win-amd64-3.8\lanedet\models\backbones
copying lanedet\models\backbones\__init__.py -> build\lib.win-amd64-3.8\lanedet\models\backbones
creating build\lib.win-amd64-3.8\lanedet\models\heads
copying lanedet\models\heads\busd.py -> build\lib.win-amd64-3.8\lanedet\models\heads
copying lanedet\models\heads\condlane.py -> build\lib.win-amd64-3.8\lanedet\models\heads
copying lanedet\models\heads\exist_head.py -> build\lib.win-amd64-3.8\lanedet\models\heads
copying lanedet\models\heads\laneatt.py -> build\lib.win-amd64-3.8\lanedet\models\heads
copying lanedet\models\heads\lane_cls.py -> build\lib.win-amd64-3.8\lanedet\models\heads
copying lanedet\models\heads\lane_seg.py -> build\lib.win-amd64-3.8\lanedet\models\heads
copying lanedet\models\heads\plain_decoder.py -> build\lib.win-amd64-3.8\lanedet\models\heads
copying lanedet\models\heads\__init__.py -> build\lib.win-amd64-3.8\lanedet\models\heads
creating build\lib.win-amd64-3.8\lanedet\models\necks
copying lanedet\models\necks\fpn.py -> build\lib.win-amd64-3.8\lanedet\models\necks
copying lanedet\models\necks\__init__.py -> build\lib.win-amd64-3.8\lanedet\models\necks
creating build\lib.win-amd64-3.8\lanedet\models\nets
copying lanedet\models\nets\detector.py -> build\lib.win-amd64-3.8\lanedet\models\nets
copying lanedet\models\nets\__init__.py -> build\lib.win-amd64-3.8\lanedet\models\nets
running egg_info
creating lanedet.egg-info
writing lanedet.egg-info\PKG-INFO
writing dependency_links to lanedet.egg-info\dependency_links.txt
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'lanedet.egg-info\SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'lanedet.egg-info\SOURCES.txt'
running build_ext
C:\Users\MINHOO\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\cpp_extension.py:304: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode 
byte 0xd3 in position 0: invalid continuation byte
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
building 'lanedet.ops.nms_impl' extension
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by Turoad** [comment]
I didn't build this repo in Windows before.
I think you can follow the error:
```
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
```

**Comment by mikaelupupup** [comment]
Did you run it successfully on the win system? There is a problem with my virtual machine and I can only try it on the win system. Currently, I have also encountered this problem and cannot solve it.
