### ISSUE TITLE
how to convert the CondLane model to onnx or pt model (include net  structure) ?

### ISSUE THREAD

**Issue by tangze5258** [Turoad/lanedet#52]
i need to covert the pth model to RKNN model to inference. The first step , the model must include net structure. so, i have tried to use torch.save  or torch.jit.trace to save the whole net ,but errors occurred. anyone konw how to do that?

**Comment by Turoad** [comment]
Currently, condlanenet is not supported to export onnx. Many operators are not supported.
If you want to, you need to write the custom operators for condlanenet.
