### ISSUE TITLE
run：python setup.py build develop，has error

### ISSUE THREAD

**Issue by 578223592** [Turoad/lanedet#54]
when i run command：python setup.py build develop ，i got 
```
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5'
E:\develop2\Anaconda3\envs\lanedet\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer
is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
running build
running build_py
running egg_info
writing lanedet.egg-info\PKG-INFO
writing dependency_links to lanedet.egg-info\dependency_links.txt
writing requirements to lanedet.egg-info\requires.txt
writing top-level names to lanedet.egg-info\top_level.txt
reading manifest file 'lanedet.egg-info\SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'lanedet.egg-info\SOURCES.txt'
creating build\lib.win-amd64-3.8\lanedet\ops\csrc
copying lanedet\ops\csrc\nms.cpp -> build\lib.win-amd64-3.8\lanedet\ops\csrc
copying lanedet\ops\csrc\nms_kernel.cu -> build\lib.win-amd64-3.8\lanedet\ops\csrc
running build_ext
E:\develop2\Anaconda3\envs\lanedet\lib\site-packages\torch\utils\cpp_extension.py:304: UserWarning: Error checking compiler version
for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
building 'lanedet.ops.nms_impl' extension
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com
/visual-cpp-build-tools/

```
I dont know what happened.
Need i install `Microsoft Visual C++ 14.0 or greater` ? Or had i  do something wrong?

**Comment by Turoad** [comment]
This issue is duplicated.
Refer this: https://github.com/Turoad/lanedet/issues/51.

**Comment by 578223592** [comment]
> This issue is duplicated. Refer this: #51.
Thanks for your replying.I got that error yesterday on windows10.(Now I guess the solution is to install a C compiler).
I ran it again on the Linux server and some other errors occurred. I blogged about these mistakes and how to fix them so that the next generation wouldn't have to face the same problem again. This is the website: https://www.cnblogs.com/swx123/p/16194224.html

**Comment by mikaelupupup** [comment]
> > This issue is duplicated. Refer this: #51.这个问题是重复的。请参考： #51 。
> > Thanks for your replying.I got that error yesterday on windows10.(Now I guess the solution is to install a C compiler). 感谢您的回复。我昨天在 windows10 上遇到了这个错误。（现在我想解决方案是安装 C 编译器）。
> > I ran it again on the Linux server and some other errors occurred. I blogged about these mistakes and how to fix them so that the next generation wouldn't have to face the same problem again. This is the website: https://www.cnblogs.com/swx123/p/16194224.html 我在Linux服务器上再次运行它，出现了一些其他错误。我在博客中介绍了这些错误以及如何修复它们，以便下一代不必再次面临同样的问题。这是网站：https://www.cnblogs.com/swx123/p/16194224.html

Did you run it successfully on the win system? There is a problem with my virtual machine and I can only try it on the win system. Currently, I have also encountered this problem and cannot solve it.

**Comment by 578223592** [comment]
> > > This issue is duplicated. Refer this: #51.这个问题是重复的。请参考： #51 。
> > > Thanks for your replying.I got that error yesterday on windows10.(Now I guess the solution is to install a C compiler). 感谢您的回复。我昨天在 windows10 上遇到了这个错误。（现在我想解决方案是安装 C 编译器）。
> > > I ran it again on the Linux server and some other errors occurred. I blogged about these mistakes and how to fix them so that the next generation wouldn't have to face the same problem again. This is the website: https://www.cnblogs.com/swx123/p/16194224.html 我在Linux服务器上再次运行它，出现了一些其他错误。我在博客中介绍了这些错误以及如何修复它们，以便下一代不必再次面临同样的问题。这是网站：https://www.cnblogs.com/swx123/p/16194224.html
> 
> Did you run it successfully on the win system? There is a problem with my virtual machine and I can only try it on the win system. Currently, I have also encountered this problem and cannot solve it.

@awslhh8 
sry,i only success on ubuntu,can't help u more.

otherwise,i think virtual machine has some diffrents with true machine on GPU,so true machine maybe a better choice .

good luck.
