### ISSUE TITLE
Unable to find model file

### ISSUE THREAD

**Issue by ajay1606** [Turoad/lanedet#56]
Hello,
Thank you so much for sharing a very much useful repository.

I have followed the step by step instructions given, and have downloaded all the datasets as mentioned in the below image

![image](https://user-images.githubusercontent.com/29722843/167053102-ead34cea-01e6-402b-8bad-c35477e6af06.png)

Training:
`python main.py configs/resa/resa50_culane.py --gpus 0`

After running the above command, i was able to see following window:
![image](https://user-images.githubusercontent.com/29722843/167053360-aa1fa3ce-1d45-48e1-b9f1-29e0b888283e.png)

But i couldn't find any model file such as `culane_resnet50.pth` ,` resa_r34_culane.pth` !! As it mentioned in the example run case.

Alternatively, is it possible to share the pre-trained model file?

As I am a beginner, I greatly appreciate your understanding and kind response.

Regards,
Ajay

**Comment by MySuperSoul** [comment]
The model and logs will save in corresponding work_dirs folder, do you check it out?

**Comment by ajay1606** [comment]
@MySuperSoul Thank you so much for your quick response. I have checked there, but i couldn't find it there also.

![image](https://user-images.githubusercontent.com/29722843/167062095-9ba16293-1230-48dd-855d-84d6990f14e8.png)

I have checked all these directories, but there were no weight files.

But there are 2 .pth file namely `11.pth` and `best.pth.`. With these file i tried to run example 

python tools/detect.py configs/resa/resa34_culane.py --img images\   --load_from /lanedet/work_dirs/CULane/20220504_091910_lr_3e-02_b_8/ckpt/best.pth --savedir ./vis

But i getting error like this.
![image](https://user-images.githubusercontent.com/29722843/167062280-31b562d8-8a02-4264-a223-644498bcfa9a.png)

Am i missing anything here ?

**Comment by Turoad** [comment]
Just rename  it, i.e., `11.pth` to `resa50_culane.pth`.
The `best.pth` is trained using resnet50 backbone. You cannot use resnet34 to load the weight. Try this:
```
python tools/detect.py configs/resa/resa50_culane.py --img images\ --load_from /lanedet/work_dirs/CULane/20220504_091910_lr_3e-02_b_8/ckpt/best.pth --savedir ./vis
```

**Comment by ajay1606** [comment]
@Turoad Thank you so much for your kind response though it's very basic questions.
Greatly appreciated and am happy to see the results (it's working well).

By the way, is there any ROS support available for this?

**Comment by Turoad** [comment]
Sorry, no ROS support.
