### ISSUE TITLE
How to specify the output lane number of condlanenet model

### ISSUE THREAD

**Issue by AvinsWang** [Turoad/lanedet#58]
I train condlanenet on my  dataset which lanes on an image maybe more than 5. The evaluation result is not right, for example, model output 5 lanes, but the gt have 10 lanes (I need the model to detect all lanes). so how to specify the lane number？Thanks.

**Comment by Turoad** [comment]
I'm not very sure. Maybe you can modify the postprocessing code, like:
https://github.com/Turoad/lanedet/blob/35665fc9dd8d80df207fa86d2152f9f48618ffe7/lanedet/models/heads/condlane.py#L274
