### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gui-hoon** [Turoad/lanedet#9]
if don't modify (from .nms import nms) from lanedet/ops/__init__.py to (from . import *) there will be an error. and  if don't modify (from . import nms_impl) from lanedet/ops/nms.py to (from . import *) there will be an error.
 And when run inference, there is no lanedet directory in the tools directory, resulting in module error from lanedet/tools/detect.py line 8~12.  Is there any other way to remove the error?

**Comment by Turoad** [comment]
Have you build the project (follow the README)?

**Comment by gui-hoon** [comment]
That's right

**Comment by Turoad** [comment]
How do you build and what's the error?
Can you show me the screenshot?

**Comment by gui-hoon** [comment]
I've solved it. Thank you.

**Comment by Omar3esam** [comment]
@gui-hoon Please what is the solution for this problem.
